- id: lint
  name: Lint JS
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.4.0'
    - eslint@8.15.0
    - eslint-config-airbnb-base@15.0.0
    - eslint-config-prettier@8.5.0
    - eslint-plugin-html@6.2.0
    - eslint-plugin-import@2.26.0
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-prettier@4.0.0
    - prettier@2.6.2
  types:
    - file
  files: \.(js|html|php)$
  exclude: (^node_modules|\.min\.js$)
